/*
 * This source file was generated by the Gradle 'init' task
 */
package app.tunde.cicd_java_docker_demo;

public class App {
    public int add(int a, int b) {
        return a + b;
    }

    public int subtract(int a, int b) {
        return a - b;
    }

    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
