/*
 * This source file was generated by the Gradle 'init' task
 */
package app.tunde.cicd_java_docker_demo;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class AppTest {
    private final App app;

    public AppTest() {
        this.app = new App();
    }
    
    @Test void add_returnsSum() {
        assertEquals(app.add(1,1), 2);
    }

    @Test void subtract_returnsDifference() {
        assertEquals(app.subtract(2,1), 1);
    }
}
